from typing import Annotated
from pydantic import Field
from core.base_classes import BaseAppModel


# "Base" model that other models can inherit from
# This does not include the ID field because
# it's not needed for creation/update (and is auto-generated by the DB)
class EntryBase(BaseAppModel):
    name: Annotated[str, Field(max_length=45)]


# Model for data returned to the client
# This includes the ID field which is generated by the database
class EntryPublic(EntryBase):
    id: int


# Model for creating a new entry. This is the same as EntryBase in this case,
# but it's defined separately for clarity and future extensibility
class EntryCreate(EntryBase):
    pass


class EntryUpdate(EntryBase):
    pass
