# Lists all available commands
list:
    just --list

# Install node libraries
install:
    npm install

# Starts the bot in development mode
dev:
    npm run dev

# Starts the bot
start:
    npm run start

# Deploys bot commands
deploy:
    npm run deploy-commands
