# Lists all available commands
list:
    just --list

# Install node libraries
install:
    yarn install

# Starts the bot in development mode
dev:
    yarn dev

# Starts the bot
start:
    yarn start

# Deploys bot commands
deploy:
    yarn deploy-commands
