# Lists all available commands
list:
    just --list

# Installs pip requirements
install:
    pip install -r requirements.txt

# =======
# API
# =======

# Starts the API in development mode
dev:
    fastapi dev

# Starts the API
start:
    fastapi run

# Generates the OpenAPI schema file
generate-openapi:
    rm -f openapi.json || true
    python generate-openapi.py
    @echo "Generated ./api/openapi.json"

# =======
# DATABASE MIGRATIONS
# =======

# Creates a new Alembic migration revision
revise *message:
    alembic revision --autogenerate -m "{{ message }}"

# Applies Alembic migrations
migrate:
    alembic upgrade head

# Rolls back the last Alembic migration
rollback:
    alembic downgrade -1
